### PR TITLE
FIX: force system_clock

### PR DESCRIPTION
**Pull request by ymontmarin**
As motioned [here](https://stackoverflow.com/questions/13263277/difference-between-stdsystem-clock-and-stdsteady-clock), `high_resolution_clock` is an alias for either `system_clock` or `steady_clock`, but in the code of hpp_util, there is a use of the method `to_time_t` which is a method only of `system_clock`, so we should force `clock_type` to alias `system_clock`.

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Comment by nim65s** [comment]
I think the point of this `Timer` is to get a relative value: the real elapsed time between the `start()` and the `stop()` calls.

If the operating system decide to adjust the `system_clock` between the `start()` and the `stop()` call this measure will be broken. This is why c++ provide a `steady_clock`, and I think we should use that one.

So I think we should either:
- remove this `to_time_t` which make no sense for the `steady_clock` we need ;
- or add a `system_start_` member to this class to display a representable time for human interpretation.

**Comment by ymontmarin** [comment]
@nim65s I propose a new solution where `clock_type` is `steady_clock` and we use `system_clock` only to print a real time from the `steady_clock` timings. Would it fit the requirements mentioned ?

**Review by nim65s — APPROVED** [review]
thanks :)

**Pull request merged**
